# -*- coding: utf-8 -*-
"""generate_carbon_by_distance.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1K4GsKc4THUeXSs3glgZQKV_Rlhf8VIS3

# Packages
"""

import pandas as pd
import numpy as np
from numpy import random

"""# Generate carbon emissions"""

def calculate_emissions(distance, emissions_factor):
  return distance*emissions_factor

def main():
  emissions_factor_car = 0.1639
  emissions_factor_bus = 0.1022
  emissions_factor_motorbike = 0.1133

  data = {
      'distance (km)': [],
      'car (kg CO2)': [],
      'bus (kg CO2)': [],
      'motorbike (kg CO2)': []
  }

  for distance in range(0, 1000):
    decimal_distance = distance / random.randint(1,10)
    car_emissions = calculate_emissions(decimal_distance, emissions_factor_car)
    bus_emissions = calculate_emissions(decimal_distance, emissions_factor_bus)
    motorbike_emissions = calculate_emissions(decimal_distance, emissions_factor_bus)

    data['distance (km)'].append(decimal_distance)
    data['car (kg CO2)'].append(car_emissions)
    data['bus (kg CO2)'].append(bus_emissions)
    data['motorbike (kg CO2)'].append(motorbike_emissions)

  dataframe = pd.DataFrame(data)
  dataframe.to_csv("carbon_emissions_by_distance.csv")

main()

"""# Dataset"""

df = pd.read_csv("/content/carbon_emissions_by_distance.csv")
df