# -*- coding: utf-8 -*-
"""plot_map.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DnkZRHYxZUdQOKwGN5X3auYqV6a40D2c

# Packages
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import folium
import os
import zipfile

"""# Dataset"""

file_paths = {
    "all_locations": "/content/all_locations.csv",
    "bandung": "/content/bandung.csv",
    "banjarbaru": "/content/banjarbaru.csv",
    "bengkulu": "/content/bengkulu.csv",
    "denpasar": "/content/denpasar.csv",
    "jakarta": "/content/jakarta.csv",
    "jayapura": "/content/jayapura.csv",
    "maluku": "/content/maluku.csv",
    "semarang": "/content/semarang.csv",
    "surabaya": "/content/surabaya.csv",
    "yogyakarta": "/content/yogyakarta.csv"
}

datasets = {key: pd.read_csv(path) for key, path in file_paths.items()}

"""# Plot map"""

def plot_map(data, popup, output_filename):
  # Initialize the map
  map = folium.Map(location=[-5.658270309200011, 115.88429310049405], zoom_start=10)

  # Adding marker to dataframe
  for i, row in data.iterrows():
    folium.Marker([row['lat'], row['long']], popup=row[popup]).add_to(map)

  # Save map to HTML format
  map.save(output_filename)

output_folder = "/plot_map"

try:
    os.makedirs(output_folder)
except FileExistsError:
    pass

for key, df in datasets.items():
    output_file = f"/{output_folder}/{key}_map.html"
    plot_map(df, 'place_name', output_file)

zip_file_name = f"{output_folder}.zip"
with zipfile.ZipFile(zip_file_name, 'w') as zipf:
    for root, dirs, files in os.walk(output_folder):
        for file in files:
            zipf.write(os.path.join(root, file), os.path.relpath(os.path.join(root, file), output_folder))